<a href="https://colab.research.google.com/github/jaimin159/SHALA2020/blob/master/Assignment_1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [0]:
import numpy as np
a = np.random.random((3,5))
b = np.random.random((3,5))
print ("Array a:", a,"\n")
print ("Array b:", b)

Array a: [[0.06095194 0.71380331 0.40567901 0.45016355 0.19066601]
 [0.03485829 0.16544508 0.75141987 0.92054287 0.86468799]
 [0.02360709 0.04251956 0.19993732 0.02157078 0.5432157 ]] 

Array b: [[0.60830883 0.65759306 0.81874044 0.49049114 0.80024167]
 [0.42765976 0.7251809  0.87122361 0.67681055 0.98798648]
 [0.28387924 0.2161652  0.2120332  0.04244201 0.25076639]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all positive integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [0]:
c = np.arange(100,dtype=int)
d = np.zeros((3,3))
print ("Array C:", c,"\n")
print ("Matrix d:", d)

Array C: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 

Matrix d: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [0]:
e = [[1,2,3],[4,5,6],[7,8,9]]
e = np.array(e)
print (e)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [0]:
f = np.ones((5,5), dtype=np.uint16)
g = np.identity(5, dtype=np.uint16)
print ("Matrix f:", f)
print ("Matrix g:", g)

Matrix f: [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Matrix g: [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [0]:
h = c.reshape(10,10)
newc = h.flatten()
if newc.shape == c.shape:
  print ("YES")
else:
  print ("NO")

YES


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.


In [0]:
A = np.random.rand(2,10,5)
newA = np.transpose(A,(1,2,0))
print ("A Transpose: ", newA)


You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [0]:
np.random.seed(0)
X = np.random.rand(10,5)
print ("Minimum value of each Column: ", np.amin(X,axis=0), "at index: " ,np.argmin(X,axis=0))
print ("Maximum value of each Column: ", np.amax(X,axis=0), "at index: " ,np.argmax(X,axis=0))
print ("Minimum value of each Row: ", np.amin(X,axis=1), "at index: " ,np.argmin(X,axis=1))
print ("Maximum value of each Row: ", np.amax(X,axis=1), "at index: " ,np.argmax(X,axis=1))
print ("Minimum value of Matrix: ", np.min(X), "at index: " ,np.argmin(X))
print ("Maximum value of Matrix: ", np.max(X), "at index: " ,np.argmax(X))

Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

In [0]:
print ("Mean of each Row: ", np.mean(X,axis=1), "Standard deviation of each Row:", np.std(X,axis=1))
print ("Mean of each column: ", np.mean(X,axis=0), "Standard deviation of each column:", np.std(X,axis=0))
print ("Mean of Matrix: ", np.mean(X), "Standard deviation of Matrix:", np.std(X))

Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [0]:
np.random.seed(3)
Y = np.random.rand(10,10)
print ("Determinant: " , np.linalg.det(Y))
print ("Rank of the Matrix: " , np.linalg.matrix_rank(Y))
print ("Diagonal Elements: ", np.diagonal(Y))
print ("Trace of Matrix: ", np.trace(Y))
print ("Eigen values of Matrix: ", np.linalg.eig(Y))
u, s, v = np.linalg.svd(Y, full_matrices=True)
print ("SVD value:", u , s , v)
try:
    invY = np.linalg.inv(Y)
except:
    invY = np.linalg.pinv(Y)
print ("Inverse of Matrix: " , invY)
print ("Multiplication  Y  with  X: ", np.matmul(Y,X))
print ("Element-wise multiplication: ", np.dot(Y, invY))

## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import pandas as pd

Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [0]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"
titanic_data = pd.read_csv(file_url)
print (titanic_data.head())



### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---



In [0]:
titanic_data_new = pd.get_dummies(titanic_data,columns=["sex","embarked","pclass"])




---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.